---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: get all jenkins agents status
    ec2_instance_facts:
      filters:
        vpc-id: vpc-id######
        "tag:JenkinsRole": agent
        "tag:GroupName": jenkins-slave-ci
      region: "us-east-1"
    register: agents_facts
    tags:
      - describe
      - start
      - stop

  - name: print agents info
    debug: var=agents_facts
    tags:
      - describe
      - start
      - stop

  - name: print instance id
    debug:
      msg: "{{item.tags.Name}} {{item.instance_id}} is {{item.state.name}}"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - describe
      - start
      - stop

  - name: Ensure agents are running
    ec2_instance:
      state: running
      instance_ids:
          - "{{ item.instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - start

  - name: Ensure agents are stopped
    ec2_instance:
      state: stopped
      instance_ids:
          - "{{ item.instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - stop

  - name: get one instance status by tag Name
    ec2_instance_facts:
      filters:
        vpc-id: vpc-6d0fac16
        "tag:JenkinsRole": agent
        "tag:GroupName": jenkins-slave-ci
        "tag:Name": "{{ ONE_INSTNACE_NAME }}"
      region: "us-east-1"
    register: one_instance_facts
    tags:
      - start-one
      - stop-one
      - describe-one

  - name: print the instance facts
    debug: var=one_instance_facts
    tags:
      - start-one
      - stop-one
      - describe-one

  - name: Check instance exists and is unique 
    fail:
      msg: "The instance not exists or not an jenkins agent"
    when: (one_instance_facts.instances| length == 0) or (one_instance_facts.instances| length > 1)
    tags:
      - start-one
      - stop-one
      - describe-one

  - name: Check instance in vpc, and is agent
    fail:
      msg: "The instance not exists or not an jenkins agent"
    when: (one_instance_facts.instances[0].vpc_id != 'vpc-id#####') or (one_instance_facts.instances[0].tags.JenkinsRole != 'agent')
    tags:
      - start-one
      - stop-one
      - describe-one

  - name: Check instance in vpc, and is ci-agent
    fail:
      msg: "The instance not exists or not an jenkins ci agent"
    when: (one_instance_facts.instances[0].vpc_id != 'vpc-id#####') or (one_instance_facts.instances[0].tags.GroupName != 'jenkins-slave-ci')
    tags:
      - start-one
      - stop-one
      - describe-one

  - name: Ensure agents are stopped
    ec2_instance:
      state: stopped
      instance_ids:
          - "{{ one_instance_facts.instances[0].instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    tags:
      - stop-one

  - name: Ensure agents are running
    ec2_instance:
      state: running
      instance_ids:
          - "{{ one_instance_facts.instances[0].instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    tags:
      - start-one