---
- hosts: 127.0.0.1
  tasks:
    
    - name: check cmake is installed 
      stat:
        path: /usr/local/share/cmake-3.11
      register: cmake_3_11_dir

    - name: Install cmake
      block:
        - name: Grab cmake
          get_url:
            url: http://www.cmake.org/files/v3.11/cmake-3.11.2.tar.gz
            dest: /home/ubuntu/tmp/cmake-3.11.2.tar.gz
        - name: unarchive the package cmake-3.11.2.tar.gz
          unarchive:
            src: /home/ubuntu/tmp/cmake-3.11.2.tar.gz
            dest: /home/ubuntu/tmp/
        - name: install cmake-3
          shell: |
             cd /home/ubuntu/tmp/cmake-3.11.2
             ./configure
             make -j4
             sudo make install
      when: cmake_3_11_dir.stat.exists == False 
