---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: get all jenkins agents status
    ec2_instance_facts:
      filters:
        "tag:GroupName": "{{ GroupName }}"
      region: "{{ REGION_NAME }}"
    register: agents_facts
    tags:
      - describe
      - start
      - stop

  - name: print agents info
    debug: var=agents_facts
    tags:
      - describe
      - start
      - stop

  - name: print instance id
    debug:
      msg: "{{item.tags.Name}} {{item.instance_id}} is {{item.state.name}}"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - describe
      - start
      - stop


  - name: Ensure agents are running
    ec2_instance:
      state: running
      instance_ids:
          - "{{ item.instance_id }}"
    environment:
      AWS_REGION: "{{ REGION_NAME }}"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - start

  - name: Ensure agents are stopped
    ec2_instance:
      state: stopped
      instance_ids:
          - "{{ item.instance_id }}"
    environment:
      AWS_REGION: "{{ REGION_NAME }}"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - stop