---
- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: get all jenkins agents status
    ec2_instance_facts:
 #https://docs.ansible.com/ansible/2.4/ec2_instance_facts_module.html
 #Gather facts about ec2 instances in AWS     
      filters:
 #filters:A dict of filters to apply.       
        "tag:GroupName": "{{ GroupName }}"
 #The AWS region to use. If not specified then the value of the AWS_REGION or EC2_REGION environment variable,       
      region: "{{ REGION_NAME }}"
# ansible的task之间还可以互相传递数据,把第一个task执行的结果register注册为变量然后传递给第二个task
    register: agents_facts
    tags:
      - describe
      - start
      - stop

  - name: print agents info
#debug: Print statements during execution 
#msg: The customized message that is printed. If omitted, prints a generic message.
#var: A variable name to debug. Mutually exclusive with the 'msg' option.  
    debug: var=agents_facts
    tags:
      - describe
      - start
      - stop

  - name: print instance id
    debug:
      msg: "{{item.tags.Name}} {{item.instance_id}} is {{item.state.name}}"
#item
    with_items: "{{ agents_facts.instances }}"
#with_items: list of items
    tags:
      - describe
      - start
      - stop
