---
- hosts: 127.0.0.1
  connection: local

  tasks:
  - name: get all jenkins agents status
    ec2_instance_facts:
      filters:
        vpc-id: vpc-id
        "tag:GroupName": tag-group-name
#filter by tag name and vpc        
      region: "us-east-1"
    register: agents_facts
    tags:
      - describe
      - start
      - stop

  - name: print agents info
    debug: var=agents_facts
#output var as agent_facts    
    tags:
      - describe
      - start
      - stop

  - name: print instance id
    debug:
      msg: "{{item.tags.Name}} {{item.instance_id}} is {{item.state.name}}"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - describe
      - start
      - stop

  - name: Ensure agents are running
    ec2_instance:
      state: running
      instance_ids:
          - "{{ item.instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - start

  - name: Ensure agents are stopped
    ec2_instance:
      state: stopped
      instance_ids:
          - "{{ item.instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    with_items: "{{ agents_facts.instances }}"
    tags:
      - stop

#get info
  - name: start one instance by tag Name
    ec2_instance_facts:
#filter by vpc-id,  tag:GroupName, tag:Name=>instance_name     
      filters:
        vpc-id: vpc-id
        "tag:GroupName": tag-group-name
        "tag:Name": "{{ ONE_INSTNACE_NAME }}"
      region: "us-east-1"
    register: one_instance_facts
    tags:
      - start-one
      - stop-one

  - name: print the instance facts
    debug: var=one_instance_facts
    tags:
      - start-one
      - stop-one

# Check instance exists and is unique 
# when: (one_instance_facts.instances| length == 0) or (one_instance_facts.instances| length > 1)
  - name: Check instance exists and is unique 
    fail:
      msg: "The instance not exists or not an jenkins agent"
    when: (one_instance_facts.instances| length == 0) or (one_instance_facts.instances| length > 1)
    tags:
      - start-one
      - stop-one

# Check instance in vpc, and is agent
# when: (one_instance_facts.instances[0].vpc_id != 'vpc-id') or (one_instance_facts.instances[0].tags.GroupName != 'tag-group-name')
  - name: Check instance in vpc, and is agent
    fail:
      msg: "The instance not exists or not an jenkins agent"
    when: (one_instance_facts.instances[0].vpc_id != 'vpc-id') or (one_instance_facts.instances[0].tags.GroupName != 'tag-group-name')
    tags:
      - start-one
      - stop-one

#stop one
  - name: Ensure agents are stopped
    ec2_instance:
      state: stopped
      instance_ids:
          - "{{ one_instance_facts.instances[0].instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    tags:
      - stop-one

#start one
  - name: Ensure agents are running
    ec2_instance:
      state: running
      instance_ids:
          - "{{ one_instance_facts.instances[0].instance_id }}"
    environment:
      AWS_REGION: "us-east-1"
    tags:
      - start-one


