- name: Check is jre1.8.0_66 installed
  stat:
    path: /usr/local/jre1.8.0_66
  register: jre_dir

- name: get jre1.8.0_66 from s3
#    command: "aws s3 cp s3://bbmobile-jenkins-archive/java/jre/jre-8u66-linux-x64.tar.gz /tmp/jre-8u66-linux-x64.tar.gz"
  aws_s3:
      bucket: bbmobile-jenkins-archive
      object: /java/jre/jre-8u66-linux-x64.tar.gz
      dest: /tmp/jre-8u66-linux-x64.tar.gz
      mode: get
      overwrite: different
  when: jre_dir.stat.exists == False


#  - name: get jre1.8.0_66 from s3
#    command: "aws s3 cp s3://bbmobile-jenkins-archive/java/jre/jre-8u66-linux-x64.tar.gz /tmp/jre-8u66-linux-x64.tar.gz"
#    when: jre_dir.stat.exists == False

- name: Get sha256 sum of script
  stat:
    path: /tmp/jre-8u66-linux-x64.tar.gz
    checksum_algorithm: sha256
    get_checksum: yes
  register: jre_8u66_stat
  when: jre_dir.stat.exists == False
  become: yes

- name: Verify sha256sum of script before execution.
  fail:
    msg: "Failure, file is not correct."
  when: (jre_dir.stat.exists == False) and
        (jre_8u66_stat.stat.checksum != 'f2249370a6ac4ca8977b66d7665179f0fef4df732f3af80b0f34567d594588bf')
  become: yes

- name: Extract jre1.8.0_66
  unarchive:
    src: '/tmp/jre-8u66-linux-x64.tar.gz'
    dest: /usr/local/
    remote_src: yes
  when: jre_dir.stat.exists == False
  become: yes

- name: Ensure owner of jre is ubuntu
  file:
    path: /usr/local/jre1.8.0_66
    owner: ubuntu
    group: ubuntu
    recurse: yes
  become: yes

- name: Install awscli via pip
  pip: >
    name=awscli
    state=latest
  become: yes  