####In sure docker prequisites installed
- name: Install the package "apt-transport-https"
  apt:
    name: apt-transport-https
    state: present
  become: yes

- name: Install the package "curl"
  apt:
    name: curl
    state: present
  become: yes

- name: Install the package "ca-certificates"
  apt:
    name: ca-certificates
    state: present
  become: yes
- name: Install the package "software-properties-common"
  apt:
    name: software-properties-common
    state: present
  become: yes

###https://docs.docker.com/install/linux/docker-ce/ubuntu/
####In sure docker installed
###Install docker
- name: Install docker
  block:
    - name: Add docker apk key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: debug lsb
      debug:
        msg: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    - name: add apt repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
    
    - name: Update repositories cache and install "docker-ce" package
      apt:
        name: docker-ce=17.12.1~ce-0~ubuntu
        update_cache: yes
    - name: add group docker
      group:
        name: docker
        state: present
    - name: add ubuntu to docker group
      user:
        name: ubuntu
        groups: ubuntu,docker
  become: yes